// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: shipping/v1/models.proto

package shipping_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingStatus int32

const (
	ShippingStatus_AWAITING_WAREHOUSE ShippingStatus = 0
	ShippingStatus_AWAITING_DISPATCH  ShippingStatus = 1
	ShippingStatus_SHIPPED            ShippingStatus = 2
	ShippingStatus_DELIVERED          ShippingStatus = 3
)

// Enum value maps for ShippingStatus.
var (
	ShippingStatus_name = map[int32]string{
		0: "AWAITING_WAREHOUSE",
		1: "AWAITING_DISPATCH",
		2: "SHIPPED",
		3: "DELIVERED",
	}
	ShippingStatus_value = map[string]int32{
		"AWAITING_WAREHOUSE": 0,
		"AWAITING_DISPATCH":  1,
		"SHIPPED":            2,
		"DELIVERED":          3,
	}
)

func (x ShippingStatus) Enum() *ShippingStatus {
	p := new(ShippingStatus)
	*p = x
	return p
}

func (x ShippingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShippingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shipping_v1_models_proto_enumTypes[0].Descriptor()
}

func (ShippingStatus) Type() protoreflect.EnumType {
	return &file_shipping_v1_models_proto_enumTypes[0]
}

func (x ShippingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShippingStatus.Descriptor instead.
func (ShippingStatus) EnumDescriptor() ([]byte, []int) {
	return file_shipping_v1_models_proto_rawDescGZIP(), []int{0}
}

type ShippingState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId  string         `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status   ShippingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=stocklet.shipping.v1.ShippingStatus" json:"status,omitempty"`
	Courier  string         `protobuf:"bytes,3,opt,name=courier,proto3" json:"courier,omitempty"`
	Tracking string         `protobuf:"bytes,4,opt,name=tracking,proto3" json:"tracking,omitempty"`
}

func (x *ShippingState) Reset() {
	*x = ShippingState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shipping_v1_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShippingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingState) ProtoMessage() {}

func (x *ShippingState) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_v1_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingState.ProtoReflect.Descriptor instead.
func (*ShippingState) Descriptor() ([]byte, []int) {
	return file_shipping_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingState) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShippingState) GetStatus() ShippingStatus {
	if x != nil {
		return x.Status
	}
	return ShippingStatus_AWAITING_WAREHOUSE
}

func (x *ShippingState) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *ShippingState) GetTracking() string {
	if x != nil {
		return x.Tracking
	}
	return ""
}

var File_shipping_v1_models_proto protoreflect.FileDescriptor

var file_shipping_v1_models_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x6c, 0x65, 0x74, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31,
	0x22, 0x9e, 0x01, 0x0a, 0x0d, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3c, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6c, 0x65, 0x74, 0x2e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x2a, 0x5b, 0x0a, 0x0e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x5f,
	0x57, 0x41, 0x52, 0x45, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x41,
	0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x44, 0x49, 0x53, 0x50, 0x41, 0x54, 0x43, 0x48,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x48, 0x49, 0x50, 0x50, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x0d, 0x0a, 0x09, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52, 0x45, 0x44, 0x10, 0x03, 0x42, 0x4b,
	0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x78,
	0x6f, 0x6c, 0x61, 0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6c, 0x65, 0x74, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x67, 0x65, 0x6e, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x3b,
	0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_shipping_v1_models_proto_rawDescOnce sync.Once
	file_shipping_v1_models_proto_rawDescData = file_shipping_v1_models_proto_rawDesc
)

func file_shipping_v1_models_proto_rawDescGZIP() []byte {
	file_shipping_v1_models_proto_rawDescOnce.Do(func() {
		file_shipping_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_shipping_v1_models_proto_rawDescData)
	})
	return file_shipping_v1_models_proto_rawDescData
}

var file_shipping_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shipping_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shipping_v1_models_proto_goTypes = []interface{}{
	(ShippingStatus)(0),   // 0: stocklet.shipping.v1.ShippingStatus
	(*ShippingState)(nil), // 1: stocklet.shipping.v1.ShippingState
}
var file_shipping_v1_models_proto_depIdxs = []int32{
	0, // 0: stocklet.shipping.v1.ShippingState.status:type_name -> stocklet.shipping.v1.ShippingStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shipping_v1_models_proto_init() }
func file_shipping_v1_models_proto_init() {
	if File_shipping_v1_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shipping_v1_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShippingState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shipping_v1_models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shipping_v1_models_proto_goTypes,
		DependencyIndexes: file_shipping_v1_models_proto_depIdxs,
		EnumInfos:         file_shipping_v1_models_proto_enumTypes,
		MessageInfos:      file_shipping_v1_models_proto_msgTypes,
	}.Build()
	File_shipping_v1_models_proto = out.File
	file_shipping_v1_models_proto_rawDesc = nil
	file_shipping_v1_models_proto_goTypes = nil
	file_shipping_v1_models_proto_depIdxs = nil
}
