version: "3.8"

services:
  edge-gateway:
    image: stocklet/edge-gateway
    build:
      context: ../../build/edge-gateway
    ports:
      - 80:80
    networks:
      - stocklet-network

  auth-service:
    image: stocklet/auth-service
    build: 
      context: ../../
      dockerfile: ../../build/auth-service/Dockerfile
    networks:
      - stocklet-network
      - stocklet-auth-network

  order-service:
    image: stocklet/order-service
    build: 
      context: ../../
      dockerfile: ../../build/order-service/Dockerfile
    networks:
      - stocklet-network
      - stocklet-order-network

  payment-service:
    image: stocklet/payment-service
    build: 
      context: ../../
      dockerfile: ../../build/payment-service/Dockerfile
    networks:
      - stocklet-network
      - stocklet-payment-network

  product-service:
    image: stocklet/product-service
    build: 
      context: ../../
      dockerfile: ../../build/product-service/Dockerfile
    networks:
      - stocklet-network
      - stocklet-product-network

  shipping-service:
    image: stocklet/shipping-service
    build: 
      context: ../../
      dockerfile: ../../build/shipping-service/Dockerfile
    networks:
      - stocklet-network
      - stocklet-shipping-network

  user-service:
    image: stocklet/user-service
    build: 
      context: ../../
      dockerfile: ../../build/user-service/Dockerfile
    networks:
      - stocklet-network
      - stocklet-user-network

  warehouse-service:
    image: stocklet/warehouse-service
    build: 
      context: ../../
      dockerfile: ../../build/warehouse-service/Dockerfile
    networks:
      - stocklet-network
      - stocklet-warehouse-network

networks:
  stocklet-network:
  stocklet-auth-network:
  stocklet-order-network:
  stocklet-payment-network:
  stocklet-product-network:
  stocklet-shipping-network:
  stocklet-user-network:
  stocklet-warehouse-network: