apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  ports:
    - name: "90"
      port: 90
      targetPort: 90
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: order-service
status:
  loadBalancer: {}
