apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: panels
build:
  artifacts:
    - image: panels/auth-service
      context: services/auth-service
      docker:
        dockerfile: Dockerfile
    - image: panels/comment-service
      context: services/comment-service
      docker:
        dockerfile: Dockerfile
    - image: panels/frontend
      context: services/frontend
      docker:
        dockerfile: Dockerfile
    - image: panels/gateway-service
      context: services/gateway-service
      docker:
        dockerfile: Dockerfile
    - image: panels/panel-service
      context: services/panel-service
      docker:
        dockerfile: Dockerfile
    - image: panels/post-service
      context: services/post-service
      docker:
        dockerfile: Dockerfile
    - image: panels/user-service
      context: services/user-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - manifests/jwtkeys-secret.yaml
    - manifests/services-configmap.yaml
    - manifest/kafka.yaml
    - manifest/frontend.yaml
    - manifest/auth-service.yaml
    - manifest/gateway-service.yaml
    - manifest/panel-service.yaml
    - manifest/post-service.yaml
    - manifest/user-service.yaml
    - manifest/comment-service.yaml
