version: "3.8"

services:
  auth-service:
    image: stocklet/auth-service
    build: 
      context: ../../
      dockerfile: ../../build/auth/Dockerfile
    networks:
      - stocklet-network
      - stocklet-auth-network

  order-service:
    image: stocklet/order-service
    build: 
      context: ../../
      dockerfile: ../../build/order/Dockerfile
    networks:
      - stocklet-network
      - stocklet-order-network

  payment-service:
    image: stocklet/payment-service
    build: 
      context: ../../
      dockerfile: ../../build/payment/Dockerfile
    networks:
      - stocklet-network
      - stocklet-payment-network

  product-service:
    image: stocklet/product-service
    build: 
      context: ../../
      dockerfile: ../../build/product/Dockerfile
    networks:
      - stocklet-network
      - stocklet-product-network

  shipping-service:
    image: stocklet/shipping-service
    build: 
      context: ../../
      dockerfile: ../../build/shipping/Dockerfile
    networks:
      - stocklet-network
      - stocklet-shipping-network

  user-service:
    image: stocklet/user-service
    build: 
      context: ../../
      dockerfile: ../../build/user/Dockerfile
    networks:
      - stocklet-network
      - stocklet-user-network

  warehouse-service:
    image: stocklet/warehouse-service
    build: 
      context: ../../
      dockerfile: ../../build/warehouse/Dockerfile
    networks:
      - stocklet-network
      - stocklet-warehouse-network

networks:
  stocklet-network:
  stocklet-auth-network:
  stocklet-order-network:
  stocklet-payment-network:
  stocklet-product-network:
  stocklet-shipping-network:
  stocklet-user-network:
  stocklet-warehouse-network: