// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: testpb/v1/test.proto

package testpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemStateEvent_Type int32

const (
	ItemStateEvent_TYPE_UNSPECIFIED ItemStateEvent_Type = 0
	ItemStateEvent_TYPE_CREATED     ItemStateEvent_Type = 1
	ItemStateEvent_TYPE_UPDATED     ItemStateEvent_Type = 2
	ItemStateEvent_TYPE_DELETED     ItemStateEvent_Type = 3
)

// Enum value maps for ItemStateEvent_Type.
var (
	ItemStateEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CREATED",
		2: "TYPE_UPDATED",
		3: "TYPE_DELETED",
	}
	ItemStateEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CREATED":     1,
		"TYPE_UPDATED":     2,
		"TYPE_DELETED":     3,
	}
)

func (x ItemStateEvent_Type) Enum() *ItemStateEvent_Type {
	p := new(ItemStateEvent_Type)
	*p = x
	return p
}

func (x ItemStateEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemStateEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_testpb_v1_test_proto_enumTypes[0].Descriptor()
}

func (ItemStateEvent_Type) Type() protoreflect.EnumType {
	return &file_testpb_v1_test_proto_enumTypes[0]
}

func (x ItemStateEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemStateEvent_Type.Descriptor instead.
func (ItemStateEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_testpb_v1_test_proto_rawDescGZIP(), []int{1, 0}
}

type TestItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *TestItem) Reset() {
	*x = TestItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_v1_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestItem) ProtoMessage() {}

func (x *TestItem) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_v1_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestItem.ProtoReflect.Descriptor instead.
func (*TestItem) Descriptor() ([]byte, []int) {
	return file_testpb_v1_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TestItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ItemStateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    ItemStateEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=testpb.v1.ItemStateEvent_Type" json:"type,omitempty"`
	Payload *TestItem           `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ItemStateEvent) Reset() {
	*x = ItemStateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_v1_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStateEvent) ProtoMessage() {}

func (x *ItemStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_v1_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStateEvent.ProtoReflect.Descriptor instead.
func (*ItemStateEvent) Descriptor() ([]byte, []int) {
	return file_testpb_v1_test_proto_rawDescGZIP(), []int{1}
}

func (x *ItemStateEvent) GetType() ItemStateEvent_Type {
	if x != nil {
		return x.Type
	}
	return ItemStateEvent_TYPE_UNSPECIFIED
}

func (x *ItemStateEvent) GetPayload() *TestItem {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetTestItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTestItemRequest) Reset() {
	*x = GetTestItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_v1_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestItemRequest) ProtoMessage() {}

func (x *GetTestItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_v1_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestItemRequest.ProtoReflect.Descriptor instead.
func (*GetTestItemRequest) Descriptor() ([]byte, []int) {
	return file_testpb_v1_test_proto_rawDescGZIP(), []int{2}
}

func (x *GetTestItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTestItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TestItem `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTestItemResponse) Reset() {
	*x = GetTestItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_v1_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestItemResponse) ProtoMessage() {}

func (x *GetTestItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_v1_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestItemResponse.ProtoReflect.Descriptor instead.
func (*GetTestItemResponse) Descriptor() ([]byte, []int) {
	return file_testpb_v1_test_proto_rawDescGZIP(), []int{3}
}

func (x *GetTestItemResponse) GetData() *TestItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateTestItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *TestItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CreateTestItemRequest) Reset() {
	*x = CreateTestItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_v1_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTestItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestItemRequest) ProtoMessage() {}

func (x *CreateTestItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_v1_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestItemRequest.ProtoReflect.Descriptor instead.
func (*CreateTestItemRequest) Descriptor() ([]byte, []int) {
	return file_testpb_v1_test_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTestItemRequest) GetItem() *TestItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateTestItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TestItem `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateTestItemResponse) Reset() {
	*x = CreateTestItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_v1_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTestItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestItemResponse) ProtoMessage() {}

func (x *CreateTestItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_v1_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestItemResponse.ProtoReflect.Descriptor instead.
func (*CreateTestItemResponse) Descriptor() ([]byte, []int) {
	return file_testpb_v1_test_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTestItemResponse) GetData() *TestItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_testpb_v1_test_proto protoreflect.FileDescriptor

var file_testpb_v1_test_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6c, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc7, 0x01,
	0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x52, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x65,
	0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x40, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22,
	0x41, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0xe5, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x63, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x1d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x71, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x20, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x3a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x0c, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6e, 0x65, 0x77, 0x42, 0x26, 0x5a, 0x24, 0x6e, 0x75,
	0x6c, 0x6c, 0x2e, 0x68, 0x65, 0x78, 0x6f, 0x6c, 0x61, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x64,
	0x65, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testpb_v1_test_proto_rawDescOnce sync.Once
	file_testpb_v1_test_proto_rawDescData = file_testpb_v1_test_proto_rawDesc
)

func file_testpb_v1_test_proto_rawDescGZIP() []byte {
	file_testpb_v1_test_proto_rawDescOnce.Do(func() {
		file_testpb_v1_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_testpb_v1_test_proto_rawDescData)
	})
	return file_testpb_v1_test_proto_rawDescData
}

var file_testpb_v1_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testpb_v1_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_testpb_v1_test_proto_goTypes = []interface{}{
	(ItemStateEvent_Type)(0),       // 0: testpb.v1.ItemStateEvent.Type
	(*TestItem)(nil),               // 1: testpb.v1.TestItem
	(*ItemStateEvent)(nil),         // 2: testpb.v1.ItemStateEvent
	(*GetTestItemRequest)(nil),     // 3: testpb.v1.GetTestItemRequest
	(*GetTestItemResponse)(nil),    // 4: testpb.v1.GetTestItemResponse
	(*CreateTestItemRequest)(nil),  // 5: testpb.v1.CreateTestItemRequest
	(*CreateTestItemResponse)(nil), // 6: testpb.v1.CreateTestItemResponse
}
var file_testpb_v1_test_proto_depIdxs = []int32{
	0, // 0: testpb.v1.ItemStateEvent.type:type_name -> testpb.v1.ItemStateEvent.Type
	1, // 1: testpb.v1.ItemStateEvent.payload:type_name -> testpb.v1.TestItem
	1, // 2: testpb.v1.GetTestItemResponse.data:type_name -> testpb.v1.TestItem
	1, // 3: testpb.v1.CreateTestItemRequest.item:type_name -> testpb.v1.TestItem
	1, // 4: testpb.v1.CreateTestItemResponse.data:type_name -> testpb.v1.TestItem
	3, // 5: testpb.v1.TestService.GetTestItem:input_type -> testpb.v1.GetTestItemRequest
	5, // 6: testpb.v1.TestService.CreateTestItem:input_type -> testpb.v1.CreateTestItemRequest
	4, // 7: testpb.v1.TestService.GetTestItem:output_type -> testpb.v1.GetTestItemResponse
	6, // 8: testpb.v1.TestService.CreateTestItem:output_type -> testpb.v1.CreateTestItemResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_testpb_v1_test_proto_init() }
func file_testpb_v1_test_proto_init() {
	if File_testpb_v1_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testpb_v1_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_v1_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemStateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_v1_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_v1_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_v1_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTestItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_v1_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTestItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testpb_v1_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testpb_v1_test_proto_goTypes,
		DependencyIndexes: file_testpb_v1_test_proto_depIdxs,
		EnumInfos:         file_testpb_v1_test_proto_enumTypes,
		MessageInfos:      file_testpb_v1_test_proto_msgTypes,
	}.Build()
	File_testpb_v1_test_proto = out.File
	file_testpb_v1_test_proto_rawDesc = nil
	file_testpb_v1_test_proto_goTypes = nil
	file_testpb_v1_test_proto_depIdxs = nil
}
