// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: service/auth_service1.proto

package protogen

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ECPublicJWK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kty string `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`
	Use string `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	Alg string `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`
	Crv string `protobuf:"bytes,4,opt,name=crv,proto3" json:"crv,omitempty"`
	X   string `protobuf:"bytes,5,opt,name=x,proto3" json:"x,omitempty"`
	Y   string `protobuf:"bytes,6,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *ECPublicJWK) Reset() {
	*x = ECPublicJWK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_service1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECPublicJWK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECPublicJWK) ProtoMessage() {}

func (x *ECPublicJWK) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_service1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECPublicJWK.ProtoReflect.Descriptor instead.
func (*ECPublicJWK) Descriptor() ([]byte, []int) {
	return file_service_auth_service1_proto_rawDescGZIP(), []int{0}
}

func (x *ECPublicJWK) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *ECPublicJWK) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *ECPublicJWK) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *ECPublicJWK) GetCrv() string {
	if x != nil {
		return x.Crv
	}
	return ""
}

func (x *ECPublicJWK) GetX() string {
	if x != nil {
		return x.X
	}
	return ""
}

func (x *ECPublicJWK) GetY() string {
	if x != nil {
		return x.Y
	}
	return ""
}

type GetJwksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetJwksRequest) Reset() {
	*x = GetJwksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_service1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJwksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwksRequest) ProtoMessage() {}

func (x *GetJwksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_service1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwksRequest.ProtoReflect.Descriptor instead.
func (*GetJwksRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_service1_proto_rawDescGZIP(), []int{1}
}

type GetJwksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*ECPublicJWK `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *GetJwksResponse) Reset() {
	*x = GetJwksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_service1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJwksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwksResponse) ProtoMessage() {}

func (x *GetJwksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_service1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwksResponse.ProtoReflect.Descriptor instead.
func (*GetJwksResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_service1_proto_rawDescGZIP(), []int{2}
}

func (x *GetJwksResponse) GetKeys() []*ECPublicJWK {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_service_auth_service1_proto protoreflect.FileDescriptor

var file_service_auth_service1_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x0b, 0x45, 0x43, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4a, 0x57, 0x4b, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x76,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x72, 0x76, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4a, 0x77,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4a, 0x77, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x43, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4a, 0x57, 0x4b,
	0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x32, 0x62, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4a, 0x77, 0x6b, 0x73,
	0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x77,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x77, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x6a, 0x77, 0x6b, 0x73, 0x42, 0x1f, 0x5a, 0x1d, 0x6e, 0x75,
	0x6c, 0x6c, 0x2e, 0x68, 0x65, 0x78, 0x6f, 0x6c, 0x61, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x64,
	0x65, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_service_auth_service1_proto_rawDescOnce sync.Once
	file_service_auth_service1_proto_rawDescData = file_service_auth_service1_proto_rawDesc
)

func file_service_auth_service1_proto_rawDescGZIP() []byte {
	file_service_auth_service1_proto_rawDescOnce.Do(func() {
		file_service_auth_service1_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_auth_service1_proto_rawDescData)
	})
	return file_service_auth_service1_proto_rawDescData
}

var file_service_auth_service1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_auth_service1_proto_goTypes = []interface{}{
	(*ECPublicJWK)(nil),     // 0: service.ECPublicJWK
	(*GetJwksRequest)(nil),  // 1: service.GetJwksRequest
	(*GetJwksResponse)(nil), // 2: service.GetJwksResponse
}
var file_service_auth_service1_proto_depIdxs = []int32{
	0, // 0: service.GetJwksResponse.keys:type_name -> service.ECPublicJWK
	1, // 1: service.AuthService.GetJwks:input_type -> service.GetJwksRequest
	2, // 2: service.AuthService.GetJwks:output_type -> service.GetJwksResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_auth_service1_proto_init() }
func file_service_auth_service1_proto_init() {
	if File_service_auth_service1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_auth_service1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECPublicJWK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_service1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJwksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_service1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJwksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_auth_service1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_auth_service1_proto_goTypes,
		DependencyIndexes: file_service_auth_service1_proto_depIdxs,
		MessageInfos:      file_service_auth_service1_proto_msgTypes,
	}.Build()
	File_service_auth_service1_proto = out.File
	file_service_auth_service1_proto_rawDesc = nil
	file_service_auth_service1_proto_goTypes = nil
	file_service_auth_service1_proto_depIdxs = nil
}
