// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: stocklet/order/v1/events.proto

package order_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderEvent_Type int32

const (
	OrderEvent_TYPE_UNSPECIFIED OrderEvent_Type = 0
	OrderEvent_TYPE_CREATED     OrderEvent_Type = 1
	OrderEvent_TYPE_UPDATED     OrderEvent_Type = 2
	OrderEvent_TYPE_DELETED     OrderEvent_Type = 3
)

// Enum value maps for OrderEvent_Type.
var (
	OrderEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CREATED",
		2: "TYPE_UPDATED",
		3: "TYPE_DELETED",
	}
	OrderEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CREATED":     1,
		"TYPE_UPDATED":     2,
		"TYPE_DELETED":     3,
	}
)

func (x OrderEvent_Type) Enum() *OrderEvent_Type {
	p := new(OrderEvent_Type)
	*p = x
	return p
}

func (x OrderEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_stocklet_order_v1_events_proto_enumTypes[0].Descriptor()
}

func (OrderEvent_Type) Type() protoreflect.EnumType {
	return &file_stocklet_order_v1_events_proto_enumTypes[0]
}

func (x OrderEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderEvent_Type.Descriptor instead.
func (OrderEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_stocklet_order_v1_events_proto_rawDescGZIP(), []int{0, 0}
}

type OrderPlacedEvent_Type int32

const (
	OrderPlacedEvent_TYPE_UNSPECIFIED OrderPlacedEvent_Type = 0
	OrderPlacedEvent_TYPE_PLACED      OrderPlacedEvent_Type = 1
)

// Enum value maps for OrderPlacedEvent_Type.
var (
	OrderPlacedEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PLACED",
	}
	OrderPlacedEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PLACED":      1,
	}
)

func (x OrderPlacedEvent_Type) Enum() *OrderPlacedEvent_Type {
	p := new(OrderPlacedEvent_Type)
	*p = x
	return p
}

func (x OrderPlacedEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderPlacedEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_stocklet_order_v1_events_proto_enumTypes[1].Descriptor()
}

func (OrderPlacedEvent_Type) Type() protoreflect.EnumType {
	return &file_stocklet_order_v1_events_proto_enumTypes[1]
}

func (x OrderPlacedEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderPlacedEvent_Type.Descriptor instead.
func (OrderPlacedEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_stocklet_order_v1_events_proto_rawDescGZIP(), []int{1, 0}
}

type OrderEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    OrderEvent_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=stocklet.order.v1.OrderEvent_Type" json:"type,omitempty"`
	Payload *OrderEvent_Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stocklet_order_v1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stocklet_order_v1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_stocklet_order_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderEvent) GetType() OrderEvent_Type {
	if x != nil {
		return x.Type
	}
	return OrderEvent_TYPE_UNSPECIFIED
}

func (x *OrderEvent) GetPayload() *OrderEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OrderPlacedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    OrderPlacedEvent_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=stocklet.order.v1.OrderPlacedEvent_Type" json:"type,omitempty"`
	Payload *OrderPlacedEvent_Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *OrderPlacedEvent) Reset() {
	*x = OrderPlacedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stocklet_order_v1_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPlacedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPlacedEvent) ProtoMessage() {}

func (x *OrderPlacedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stocklet_order_v1_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPlacedEvent.ProtoReflect.Descriptor instead.
func (*OrderPlacedEvent) Descriptor() ([]byte, []int) {
	return file_stocklet_order_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderPlacedEvent) GetType() OrderPlacedEvent_Type {
	if x != nil {
		return x.Type
	}
	return OrderPlacedEvent_TYPE_UNSPECIFIED
}

func (x *OrderPlacedEvent) GetPayload() *OrderPlacedEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OrderEvent_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *OrderEvent_Payload) Reset() {
	*x = OrderEvent_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stocklet_order_v1_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent_Payload) ProtoMessage() {}

func (x *OrderEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_stocklet_order_v1_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent_Payload.ProtoReflect.Descriptor instead.
func (*OrderEvent_Payload) Descriptor() ([]byte, []int) {
	return file_stocklet_order_v1_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OrderEvent_Payload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderPlacedEvent_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderPlacedEvent_Payload) Reset() {
	*x = OrderPlacedEvent_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stocklet_order_v1_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPlacedEvent_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPlacedEvent_Payload) ProtoMessage() {}

func (x *OrderPlacedEvent_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_stocklet_order_v1_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPlacedEvent_Payload.ProtoReflect.Descriptor instead.
func (*OrderPlacedEvent_Payload) Descriptor() ([]byte, []int) {
	return file_stocklet_order_v1_events_proto_rawDescGZIP(), []int{1, 0}
}

var File_stocklet_order_v1_events_proto protoreflect.FileDescriptor

var file_stocklet_order_v1_events_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6c, 0x65, 0x74, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6c, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0xff, 0x01, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x36, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6c, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x6c, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x24, 0x0a, 0x07, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x52, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x44, 0x10, 0x03, 0x22, 0xd1, 0x01, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x6c, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x45, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x6c, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a,
	0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2d, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x44, 0x10, 0x01, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x78, 0x6f, 0x6c, 0x61, 0x6e, 0x2f,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6c, 0x65, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stocklet_order_v1_events_proto_rawDescOnce sync.Once
	file_stocklet_order_v1_events_proto_rawDescData = file_stocklet_order_v1_events_proto_rawDesc
)

func file_stocklet_order_v1_events_proto_rawDescGZIP() []byte {
	file_stocklet_order_v1_events_proto_rawDescOnce.Do(func() {
		file_stocklet_order_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_stocklet_order_v1_events_proto_rawDescData)
	})
	return file_stocklet_order_v1_events_proto_rawDescData
}

var file_stocklet_order_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stocklet_order_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stocklet_order_v1_events_proto_goTypes = []interface{}{
	(OrderEvent_Type)(0),             // 0: stocklet.order.v1.OrderEvent.Type
	(OrderPlacedEvent_Type)(0),       // 1: stocklet.order.v1.OrderPlacedEvent.Type
	(*OrderEvent)(nil),               // 2: stocklet.order.v1.OrderEvent
	(*OrderPlacedEvent)(nil),         // 3: stocklet.order.v1.OrderPlacedEvent
	(*OrderEvent_Payload)(nil),       // 4: stocklet.order.v1.OrderEvent.Payload
	(*OrderPlacedEvent_Payload)(nil), // 5: stocklet.order.v1.OrderPlacedEvent.Payload
}
var file_stocklet_order_v1_events_proto_depIdxs = []int32{
	0, // 0: stocklet.order.v1.OrderEvent.type:type_name -> stocklet.order.v1.OrderEvent.Type
	4, // 1: stocklet.order.v1.OrderEvent.payload:type_name -> stocklet.order.v1.OrderEvent.Payload
	1, // 2: stocklet.order.v1.OrderPlacedEvent.type:type_name -> stocklet.order.v1.OrderPlacedEvent.Type
	5, // 3: stocklet.order.v1.OrderPlacedEvent.payload:type_name -> stocklet.order.v1.OrderPlacedEvent.Payload
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_stocklet_order_v1_events_proto_init() }
func file_stocklet_order_v1_events_proto_init() {
	if File_stocklet_order_v1_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stocklet_order_v1_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stocklet_order_v1_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPlacedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stocklet_order_v1_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderEvent_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stocklet_order_v1_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPlacedEvent_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stocklet_order_v1_events_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stocklet_order_v1_events_proto_goTypes,
		DependencyIndexes: file_stocklet_order_v1_events_proto_depIdxs,
		EnumInfos:         file_stocklet_order_v1_events_proto_enumTypes,
		MessageInfos:      file_stocklet_order_v1_events_proto_msgTypes,
	}.Build()
	File_stocklet_order_v1_events_proto = out.File
	file_stocklet_order_v1_events_proto_rawDesc = nil
	file_stocklet_order_v1_events_proto_goTypes = nil
	file_stocklet_order_v1_events_proto_depIdxs = nil
}
