[tool.poetry]
name = "http-simple-order-orchestration-json"
version = "0.1.0"
description = ""
authors = ["Declan <declan@hexolan.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
