version: "3.8"

services:
  # Core Infra
  debezium:
    ports:
      - 8083:8083

  # Services
  auth-service:
    ports:
      - 91:90
      - 9091:9090
      
  order-service:
    ports:
      - 92:90
      - 9092:9090

  # Development Utilities
  dev-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:19092"
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - 8080:8080
    networks:
      - stocklet-network

  dev-adminer:
    image: adminer:latest
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: "auth-service-postgres:5432"
    ports:
      - 8081:8080
    networks:
      - stocklet-auth-network
      - stocklet-order-network