swagger: "2.0"
info:
  title: stocklet/auth/v1/types.proto
  version: version not set
tags:
  - name: AuthService
  - name: OrderService
  - name: PaymentService
  - name: ProductService
  - name: ShippingService
  - name: UserService
  - name: WarehouseService
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/auth/login:
    post:
      operationId: AuthService_LoginPassword
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1LoginPasswordResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1LoginPasswordRequest'
      tags:
        - AuthService
  /v1/auth/password:
    post:
      operationId: AuthService_SetPassword
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SetPasswordResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SetPasswordRequest'
      tags:
        - AuthService
  /v1/order/list:
    get:
      operationId: OrderService_GetOrders
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetOrdersResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: customerId
          in: query
          required: false
          type: string
      tags:
        - OrderService
  /v1/order/new:
    post:
      operationId: OrderService_CreateOrder
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateOrderResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: order
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1Order'
      tags:
        - OrderService
  /v1/order/{order.id}:
    post:
      operationId: OrderService_UpdateOrder
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateOrderResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: order.id
          in: path
          required: true
          type: string
        - name: order
          in: body
          required: true
          schema:
            type: object
            properties:
              status:
                $ref: '#/definitions/v1OrderStatus'
              items:
                type: array
                items:
                  type: object
                  $ref: '#/definitions/orderv1OrderItem'
              customerId:
                type: string
              transactionId:
                type: string
              createdAt:
                type: string
                format: int64
      tags:
        - OrderService
  /v1/order/{orderId}:
    get:
      operationId: OrderService_GetOrder
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetOrderResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: orderId
          in: path
          required: true
          type: string
      tags:
        - OrderService
    delete:
      operationId: OrderService_CancelOrder
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CancelOrderResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: orderId
          in: path
          required: true
          type: string
      tags:
        - OrderService
  /v1/payment/balance:
    get:
      operationId: PaymentService_GetBalance
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetBalanceResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      tags:
        - PaymentService
  /v1/product/item/{productId}:
    get:
      operationId: ProductService_GetProduct
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetProductResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: productId
          in: path
          required: true
          type: string
      tags:
        - ProductService
    delete:
      operationId: ProductService_DeleteProduct
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DeleteProductResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: productId
          in: path
          required: true
          type: string
      tags:
        - ProductService
    post:
      operationId: ProductService_UpdateProduct
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateProductResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: productId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
      tags:
        - ProductService
  /v1/product/items:
    get:
      operationId: ProductService_GetProducts
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetProductsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      tags:
        - ProductService
  /v1/product/new:
    post:
      operationId: ProductService_CreateProduct
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateProductResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateProductRequest'
      tags:
        - ProductService
  /v1/shipping/order/{orderId}:
    get:
      operationId: ShippingService_GetShippingDetails
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetShippingDetailsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: orderId
          in: path
          required: true
          type: string
      tags:
        - ShippingService
    post:
      operationId: ShippingService_UpdateShippingStatus
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateShippingStatusResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: orderId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
      tags:
        - ShippingService
  /v1/user/id/{userId}:
    get:
      operationId: UserService_GetUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      tags:
        - UserService
    delete:
      operationId: UserService_DeleteUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DeleteUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: userId
          in: path
          required: true
          type: string
      tags:
        - UserService
    post:
      operationId: UserService_UpdateUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: userId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
      tags:
        - UserService
  /v1/user/new:
    post:
      operationId: UserService_CreateUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateUserRequest'
      tags:
        - UserService
  /v1/warehouse/product/{productId}:
    get:
      operationId: WarehouseService_GetProductStock
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetProductStockResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: productId
          in: path
          required: true
          type: string
      tags:
        - WarehouseService
    post:
      operationId: WarehouseService_UpdateProductStock
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateProductStockResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: productId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
      tags:
        - WarehouseService
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  orderv1OrderItem:
    type: object
    properties:
      productId:
        type: string
      quantity:
        type: integer
        format: int32
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  v1AuthToken:
    type: object
    properties:
      tokenType:
        type: string
      accessToken:
        type: string
      expiresIn:
        type: string
        format: int64
  v1CancelOrderResponse:
    type: object
  v1CreateOrderResponse:
    type: object
    properties:
      data:
        $ref: '#/definitions/v1Order'
  v1CreateProductRequest:
    type: object
  v1CreateProductResponse:
    type: object
  v1CreateUserRequest:
    type: object
  v1CreateUserResponse:
    type: object
  v1DeleteProductResponse:
    type: object
  v1DeleteUserResponse:
    type: object
  v1GetBalanceResponse:
    type: object
    properties:
      userId:
        type: string
      balance:
        type: number
        format: float
  v1GetOrderResponse:
    type: object
    example:
      data:
        id: "123"
    properties:
      data:
        $ref: '#/definitions/v1Order'
    description: abcdef
    title: Order Response
  v1GetOrdersResponse:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Order'
  v1GetProductResponse:
    type: object
  v1GetProductStockResponse:
    type: object
  v1GetProductsResponse:
    type: object
  v1GetShippingDetailsResponse:
    type: object
  v1GetUserResponse:
    type: object
  v1LoginPasswordRequest:
    type: object
    properties:
      userId:
        type: string
      password:
        type: string
    required:
      - userId
      - password
  v1LoginPasswordResponse:
    type: object
    properties:
      detail:
        type: string
      data:
        $ref: '#/definitions/v1AuthToken'
  v1Order:
    type: object
    properties:
      id:
        type: string
      status:
        $ref: '#/definitions/v1OrderStatus'
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/orderv1OrderItem'
      customerId:
        type: string
      transactionId:
        type: string
      createdAt:
        type: string
        format: int64
  v1OrderStatus:
    type: string
    enum:
      - ORDER_STATUS_UNSPECIFIED
      - ORDER_STATUS_PENDING
      - ORDER_STATUS_REJECTED
      - ORDER_STATUS_CANCELLED
      - ORDER_STATUS_APPROVED
      - ORDER_STATUS_SUCCESS
    default: ORDER_STATUS_UNSPECIFIED
    title: |-
      todo: work on models
      todo: event schemas
  v1SetPasswordRequest:
    type: object
    properties:
      userId:
        type: string
      password:
        type: string
    required:
      - userId
      - password
  v1SetPasswordResponse:
    type: object
    properties:
      detail:
        type: string
  v1UpdateOrderResponse:
    type: object
  v1UpdateProductResponse:
    type: object
  v1UpdateProductStockResponse:
    type: object
  v1UpdateShippingStatusResponse:
    type: object
  v1UpdateUserResponse:
    type: object
