// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: order/v1/events.proto

package order_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreateEventType int32

const (
	OrderCreateEventType_PAYMENT_APPROVED OrderCreateEventType = 0
	OrderCreateEventType_PAYMENT_REJECTED OrderCreateEventType = 1
	OrderCreateEventType_STOCK_RESERVED   OrderCreateEventType = 2
	OrderCreateEventType_STOCK_REJECTED   OrderCreateEventType = 3
)

// Enum value maps for OrderCreateEventType.
var (
	OrderCreateEventType_name = map[int32]string{
		0: "PAYMENT_APPROVED",
		1: "PAYMENT_REJECTED",
		2: "STOCK_RESERVED",
		3: "STOCK_REJECTED",
	}
	OrderCreateEventType_value = map[string]int32{
		"PAYMENT_APPROVED": 0,
		"PAYMENT_REJECTED": 1,
		"STOCK_RESERVED":   2,
		"STOCK_REJECTED":   3,
	}
)

func (x OrderCreateEventType) Enum() *OrderCreateEventType {
	p := new(OrderCreateEventType)
	*p = x
	return p
}

func (x OrderCreateEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderCreateEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_events_proto_enumTypes[0].Descriptor()
}

func (OrderCreateEventType) Type() protoreflect.EnumType {
	return &file_order_v1_events_proto_enumTypes[0]
}

func (x OrderCreateEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderCreateEventType.Descriptor instead.
func (OrderCreateEventType) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_events_proto_rawDescGZIP(), []int{0}
}

type OrderCreateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       OrderCreateEventType `protobuf:"varint,1,opt,name=type,proto3,enum=stocklet.order.v1.OrderCreateEventType" json:"type,omitempty"`
	OrderId    string               `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId string               `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *OrderCreateEvent) Reset() {
	*x = OrderCreateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_v1_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateEvent) ProtoMessage() {}

func (x *OrderCreateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateEvent.ProtoReflect.Descriptor instead.
func (*OrderCreateEvent) Descriptor() ([]byte, []int) {
	return file_order_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreateEvent) GetType() OrderCreateEventType {
	if x != nil {
		return x.Type
	}
	return OrderCreateEventType_PAYMENT_APPROVED
}

func (x *OrderCreateEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreateEvent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

var File_order_v1_events_proto protoreflect.FileDescriptor

var file_order_v1_events_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6c, 0x65,
	0x74, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x8b, 0x01, 0x0a, 0x10, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x3b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x6c, 0x65, 0x74, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x2a, 0x6a, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x50, 0x50, 0x52,
	0x4f, 0x56, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x53, 0x54, 0x4f, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x4f, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54,
	0x45, 0x44, 0x10, 0x03, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x78, 0x6f, 0x6c, 0x61, 0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x6c, 0x65, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_order_v1_events_proto_rawDescOnce sync.Once
	file_order_v1_events_proto_rawDescData = file_order_v1_events_proto_rawDesc
)

func file_order_v1_events_proto_rawDescGZIP() []byte {
	file_order_v1_events_proto_rawDescOnce.Do(func() {
		file_order_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_v1_events_proto_rawDescData)
	})
	return file_order_v1_events_proto_rawDescData
}

var file_order_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_v1_events_proto_goTypes = []interface{}{
	(OrderCreateEventType)(0), // 0: stocklet.order.v1.OrderCreateEventType
	(*OrderCreateEvent)(nil),  // 1: stocklet.order.v1.OrderCreateEvent
}
var file_order_v1_events_proto_depIdxs = []int32{
	0, // 0: stocklet.order.v1.OrderCreateEvent.type:type_name -> stocklet.order.v1.OrderCreateEventType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_v1_events_proto_init() }
func file_order_v1_events_proto_init() {
	if File_order_v1_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_v1_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_v1_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_v1_events_proto_goTypes,
		DependencyIndexes: file_order_v1_events_proto_depIdxs,
		EnumInfos:         file_order_v1_events_proto_enumTypes,
		MessageInfos:      file_order_v1_events_proto_msgTypes,
	}.Build()
	File_order_v1_events_proto = out.File
	file_order_v1_events_proto_rawDesc = nil
	file_order_v1_events_proto_goTypes = nil
	file_order_v1_events_proto_depIdxs = nil
}
